"""First migration

Revision ID: 80ff5f0f9e18
Revises: 
Create Date: 2023-05-14 02:33:56.689464

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "80ff5f0f9e18"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "studycategory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_studycategory_title"), "studycategory", ["title"], unique=False
    )
    op.create_table(
        "userprofile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("favorite_color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_userprofile_user_id"), "userprofile", ["user_id"], unique=True
    )
    op.create_table(
        "dailygoal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("block_size", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["userprofile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dailygoal_user_id"), "dailygoal", ["user_id"], unique=False
    )
    op.create_table(
        "userprofilecategorylink",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("study_category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_category_id"],
            ["studycategory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["userprofile.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "study_category_id"),
    )
    op.create_table(
        "studyblock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("daily_goal_id", sa.Integer(), nullable=False),
        sa.Column("study_category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["daily_goal_id"],
            ["dailygoal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["study_category_id"],
            ["studycategory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["userprofile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_studyblock_daily_goal_id"),
        "studyblock",
        ["daily_goal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_studyblock_study_category_id"),
        "studyblock",
        ["study_category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_studyblock_user_id"), "studyblock", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_studyblock_user_id"), table_name="studyblock")
    op.drop_index(op.f("ix_studyblock_study_category_id"), table_name="studyblock")
    op.drop_index(op.f("ix_studyblock_daily_goal_id"), table_name="studyblock")
    op.drop_table("studyblock")
    op.drop_table("userprofilecategorylink")
    op.drop_index(op.f("ix_dailygoal_user_id"), table_name="dailygoal")
    op.drop_table("dailygoal")
    op.drop_index(op.f("ix_userprofile_user_id"), table_name="userprofile")
    op.drop_table("userprofile")
    op.drop_index(op.f("ix_studycategory_title"), table_name="studycategory")
    op.drop_table("studycategory")
    # ### end Alembic commands ###
