"""First migration

Revision ID: a41190e7fef5
Revises: 
Create Date: 2023-05-13 06:32:54.888720

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a41190e7fef5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studycategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('dailygoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('block_size', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailygoal_user_profile_id'), 'dailygoal', ['user_profile_id'], unique=False)
    op.create_table('userprofilecategorylink',
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('study_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_category_id'], ['studycategory.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('user_profile_id', 'study_category_id')
    )
    op.create_table('studyblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('daily_goal_id', sa.Integer(), nullable=False),
    sa.Column('study_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_goal_id'], ['dailygoal.id'], ),
    sa.ForeignKeyConstraint(['study_category_id'], ['studycategory.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studyblock')
    op.drop_table('userprofilecategorylink')
    op.drop_index(op.f('ix_dailygoal_user_profile_id'), table_name='dailygoal')
    op.drop_table('dailygoal')
    op.drop_table('userprofile')
    op.drop_table('studycategory')
    # ### end Alembic commands ###
