"""Add disabled field

Revision ID: 7d99720b54b8
Revises: b2b2e6e5e035
Create Date: 2023-05-11 08:54:00.773520

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "7d99720b54b8"
down_revision = "b2b2e6e5e035"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("disabled", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "disabled")
    # ### end Alembic commands ###
